### ISSUE TITLE
rm -rf .git does not work in Windows

### ISSUE THREAD

**Issue by RDrathi** [salto-io/salesforce-cicd-template#1]
When I tried to remove the relationship between the local repository and remote repository by using this command "**rm -rf .git**" in windows, it threw me an error saying - 
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:4
+ rm -rf .git
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
![rm_rf_error](https://github.com/salto-io/salesforce-cicd-template/assets/50052351/a3e9a644-5bd8-4a90-8bee-9d47fdc137e8)

After much research I finally landed on the right command which is **_rm -Force .git_**
![rm_force](https://github.com/salto-io/salesforce-cicd-template/assets/50052351/bc090f9a-7c63-4009-afcc-aa7a98a376d5)

**Comment by pgonzaleznetwork** [comment]
@RDrathi thanks a lot for bringing this up, and thank you for your research! I've added the command you provided to the readme file. Thanks again and good luck with the course!

**Comment by RDrathi** [comment]
You are most welcome.
